# -*- coding: utf-8 -*-
"""Villain Bouncer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTQ0n9SZoGHdVPdnqWaaH0MADRPtkQiv
"""

#Villain Bouncer
import time
import sys
print("**************VILLAIN ACADEMY**************")
print("----------------WELCOME!!----------------")

name = input("What's your name?\n").strip().capitalize()
good_people = {"Krishnaji","Shivaji","Jesus","Buddha","Durga maa", "Mary"} #etc etc. too many good people. welp
if name in good_people :
 print(f"This place is only for evil people, {name}. You are too pure.")
 sys.exit()
else:
 print(f"Welcome to The Villain Academy {name}. But before I let you in, you have to prove your evilness.")

villain_story = input("Do you have any tragic backstory?\n")
if "y" in villain_story.lower() :
   print("Cool. Submit the copy of your story in the corner...")
else:
    print("GET OUT!")
    time.sleep(1)
    print("Villain Gate shutting down...")
    time.sleep(1)
    sys.exit()


villain_laugh = input("Now show me your laugh.\n")

print("Analysing your aura...")
time.sleep(2)

if "HEHE" in villain_laugh.upper():
    print(f"Diabolical. You pass {name}.")
elif "HAHA" in villain_laugh.upper():
    print(f"Classic. Accepted, The Future Villain {name}.")
else:
    print("That was cute... GET OUT!")
    sys.exit()

with open("villain_logs.txt", "a") as log:
  log.write(f"{name} - Backstory: Approved | Villain laugh: {villain_laugh}\n")

with open("villain_logs.txt", "r") as file:
  logs = file.read()
  print(logs)

  """
  today i learnt how to make a bouncer by python and how to reject pure people and let in the people with backstories.
  I learnt that spelling is villain not villian.
  I learnt that colab has personal grudges against me.
  I learnt how to use w, a and r and file management for my future villain company.
  I learnt that benty laughs as HEHEHEHEH. so scary.
  and yes, i learnt that we can import tkinter as potato.
  """